# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'productsearch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for productsearch

  target 'productsearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'productsearchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'AFNetworking', '~> 2.6'
pod 'ORStackView', '~> 3.0'
pod 'SwiftyJSON', '~> 4.0'
pod 'Alamofire'
pod 'McPicker', '~> 2.0.0'
pod 'Toast-Swift', '~> 4.0.0'
pod "SwiftSpinner"
pod 'INTULocationManager'


end
